#!/usr/bin/env bash

cd ${0%/*}
source dotfiles.conf;

# if [[ $# != 0 ]]; then
# 	export "$@"
# fi

## SYM LINK DOTFILES ###########################################################
"${init}"/.initDotfiles.sh;

#cd "${config_dir}"
## PROMPT TO INSTALL VIM PLUGINS ###############################################
shouldInitZsh=0
if [[ "$*" =~ ^[-]*[fF]{1}(orce)*$ ]]; then
  shouldInitZsh=1;
else
  printf "\n";
  read -t 20 -p "Install the ZSH shell settings and install ZSH plugins? (y/n) " -n 1
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    shouldInitZsh=1;
  fi 
fi

## PROMPT TO INSTALL VIM PLUGINS ###############################################
shouldInitVIM=0
if [[ "$*" =~ ^[-]*[fF]{1}(orce)*$ ]]; then
  shouldInitVIM=1;
else
  printf "\n";
  read -t 20 -p "Update VIM settings and install VIM plugins? (y/n) " -n 1
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    shouldInitVIM=1;
  fi
fi

## PROMPT TO INSTALL HOMEBREW ##################################################
shouldInitBrew=0
if [[ "$*" =~ ^[-]?[fF]{1}(orce)*$ ]]; then
  shouldInitBrew=1;
else
  printf "\n";
  read -t 20 -p "Install Homebrew, Git and other useful homebrew dependencies? (y/n) " -n 1
  if [[ $REPLY =~ ^[Yy]$ ]]; then
      shouldInitBrew=1;
  fi
fi

## PROMPT TO INSTALL CASK ######################################################
shouldInitCask=0
if [[ "$*" =~ ^[-]?[fF]{1}(orce)*$ ]]; then
    shouldInitCask=1;
else
  printf "\n";
  read -t 20 -p "Install brew-cask? (y/n) " -n 1
  if [[ $REPLY =~ ^[Yy]$ ]]; then
      shouldInitCask=1;
  fi
fi

## PROMPT TO INSTALL TERMINAL PROFILE ##########################################
shouldInitTerm=0
if [[ "$*" =~ ^[-]*[fF]{1}(orce)*$ ]]; then
  shouldInitTerm=1;
else
  printf "\n";
  read -t 20 -p "Update terminal settings/themes? (y/n) " -n 1
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    shouldInitTerm=1;
  fi
fi

shouldRunOSX=0;
shouldInitAlcatraz=0;
function setupMac() {
  ## PROMPT TO RUN .OSX.sh #####################################################
  if [[ "$*" =~ ^[-]?[fF]{1}(orce)*$ ]]; then
      shouldRunOSX=1;
  else
    printf "\n";
    read -t 20 -p "Run .osx.sh? This will overwrite existing settings on your Mac. Are you sure? (y/n) " -n 1
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        shouldRunOSX=1;
    fi
  fi

  ## PROMPT TO INSTALL ALCATRAZ ################################################
  if [[ "$*" =~ ^[-]?[fF]{1}(orce)*$ ]]; then
      shouldInitAlcatraz=1;
  else
    printf "\n";
    read -t 20 -p "Install Alcatraz package manager for Xcode? (y/n) " -n 1
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        shouldInitAlcatraz=1;
    fi
  fi
}

function setupLinux() {
  # replace gedit with atom as the default text editor
  sudo sed -i 's/gedit/vim/' /usr/share/applications/defaults.list

  # set workspaces to be 3x3
  # gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ vsize 3
  # gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ hsize 3
}

if [[ "$OSTYPE" =~ ^(linux)+ ]]; then
  setupLinux;
elif [[ "$OSTYPE" =~ ^(darwin)+ ]]; then
  setupMac "$@";
fi

## RUN THE APPROPRIATE INSTALLERS ##############################################
if [[ ${shouldInitZsh} == 1 ]]; then
  "${init}"/.initZsh.sh;
fi

if [[ ${shouldInitVIM} == 1 ]]; then
  "${init}"/.initVIM.sh;
fi

if [[ ${shouldInitBrew} == 1 ]]; then
  "${init}"/.initBrew.sh;
fi

if [[ ${shouldInitCask} == 1 ]]; then
  "${init}"/.initCask.sh;
fi

if [[ ${shouldInitTerm} == 1 ]]; then
  "${init}"/.initTerminal.sh;
fi

if [[ ${shouldInitAlcatraz} == 1 ]]; then
  "${init}"/.initAlcatraz.sh;
fi

if [[ ${shouldRunOSX} == 1 ]]; then
  "${init}"/.osx.sh;
fi

#printf "\nReloading shell..."
#exec $SHELL -l

exit 0;
